# Site Settings
title: 纳福素材
email: nafjapan@yahoo.co.jp
description: 一站式素材.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://nafjapan.github.io" # the base hostname & protocol for your site
google_analytics: "UA-XXXXXXXX-X"

# User Settings
username: 纳福素材
user_description: 素材太多了啊.
disqus_username: disqus_username

# Social Media
# Remove the item if you don't need it
github_username: nafjapan
facebook_username: nafjapan
twitter_username: nafjapan
instagram_username: nafjapan
linkedin_username: nafjapan
medium_username: nafjapan

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
paginate: 24
paginate_path: "/page/:num/"
svg_color: "#ff0a16"

# Plugins
plugins:
  - jemoji
  - jekyll-paginate

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Contact
    url: /contact/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
